### ISSUE TITLE
.env 위치를 스프링부트 프로젝트 내에 생성하기 버그 수정

### ISSUE THREAD

**Issue by j2noo** [Team-ReMind/ReMind-BE#17]
## Description
**이슈에 대해 설명해 주세요.**

## Etc
**기타 공유사항에 대해 작성해 주세요.**

**Comment by lsm-del** [comment]
@j2noo 

docker에서 외부 데이터 인식하는 방법 레퍼런스
https://docs.docker.com/storage/
